CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` varchar(50) NOT NULL DEFAULT '' COMMENT '名称',
  `avatar` varchar(150) NOT NULL DEFAULT '' COMMENT '头像',
  `mobile` char(11) NOT NULL DEFAULT '' COMMENT '手机号',
  `gender` tinyint(1) NOT NULL DEFAULT '2' COMMENT '性别：0-女，1-男，2-未知',
  `qq` varchar(50) NOT NULL DEFAULT '' COMMENT 'qq',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT 'email',
  `password` char(12) NOT NULL DEFAULT '' COMMENT '密码',
  `invited_user_id` int(11) NOT NULL COMMENT '邀请人',
  `invite_code` varchar(50) NOT NULL DEFAULT '' COMMENT '邀请码',
  `role` tinyint(1) NOT NULL DEFAULT '0' COMMENT '角色：0-普通，1-买家，2-卖家',
  `level` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '等级',
  `open_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '任务开启状态：0-否，1-是',
  `taobao_account` varchar(100) NOT NULL DEFAULT '' COMMENT '淘宝账户',
  `jd_account` varchar(100) NOT NULL DEFAULT '' COMMENT '京东账户',
  `token` char(32) NOT NULL DEFAULT '' COMMENT 'token',
  `token_expires` int(11) NOT NULL DEFAULT '0' COMMENT '过期时间',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mobile` (`mobile`),
  UNIQUE KEY `idx_token` (`token`),
  KEY `idx_role` (`role`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='用户表';